### ISSUE TITLE
CUBETOUCH 1s (3yqdo5yt) not supported

### ISSUE THREAD

**Issue by damiano75** [PlusPlus-ua/ha_tuya_ble#7] opened 2023-04-28 10:24 UTC
Integration doesn't create any switch or controls for my CUBETOUCH 1s (3yqdo5yt), only the signal strength sensor

![image](https://user-images.githubusercontent.com/47896789/235122920-c560d4ff-2ecf-4572-981e-31ef9edee317.png)

**Comment by PlusPlus-ua** [comment] 2023-04-28 10:40
Could you please provide "Device debugging" from Tuya IOT Platform?

You have to login to https://iot.tuya.com/ then select Cloud on the left, select your project, Devices tab, click "Debug device" in CUBETOUCH device row, Device Debugging tab, copy text below Standard Instruction Set.

I suppose datapoints of CUBETOUCH 1 must be identical to CUBETOUCH II, so only adding product_id will be needed.

**Comment by damiano75** [comment] 2023-04-28 10:47
This is a screenshot

![image](https://user-images.githubusercontent.com/47896789/235128009-e5aed9ce-3dd4-41fe-9c59-5a30869e726a.png)

**Comment by damiano75** [comment] 2023-04-28 10:50
<html>
<body>


switch | Boolean | "{true,false}"
-- | -- | --
mode | Enum | {   "range": [     "click"   ] }
click_sustain_time | Integer | {   "unit": "s",   "min": 0,   "max": 10,   "scale": 0,   "step": 1 }
arm_up_percent | Integer | {   "unit": "%",   "min": 0,   "max": 100,   "scale": 0,   "step": 1 }
arm_down_percent | Integer | {   "unit": "%",   "min": 0,   "max": 100,   "scale": 0,   "step": 1 }
power_saving | Boolean | "{true,false}"
tap_enable | Boolean | "{true,false}"


</body>
</html>

**Comment by PlusPlus-ua** [comment] 2023-04-28 11:10
CUBETOUCH II doesn't have power_saving and tap_enable.

Has your device any buttons for manual control? In mobile application is there something corresponding to "power_saving"?

I think it's better to recheck id's of all datapoints. Here is described how to do it:

https://www.zigbee2mqtt.io/advanced/support-new-devices/03_find_tuya_data_points.html#_9-find-your-data-point

**Comment by damiano75** [comment] 2023-04-28 12:44
> CUBETOUCH II doesn't have power_saving and tap_enable.
> 
> Has your device any buttons for manual control?

Only an on/off switch

> In mobile application is there something corresponding to "power_saving"?

No

> I think it's better to recheck id's of all datapoints. Here is described how to do it:
> 
> https://www.zigbee2mqtt.io/advanced/support-new-devices/03_find_tuya_data_points.html#_9-find-your-data-point

If I understood the instructions:

<html>
<body>


Data Point | Code 
-- | -- 
switch | 1
mode | 2
click_sustain_time | 3
control_back | 4
arm_up_percent | 5
arm_down_percent | 6
charge_status| 7
battery_percentage | 8
power_saving | 9
tap_enable | 10
program | 11


</body>
</html>

**Comment by PlusPlus-ua** [comment] 2023-04-28 14:09
Yes, that's what I've expected, thank you.

I'll add the device with power_saving and tap_enable as switch entities. So, you will be able to check what these switches do on real device. Then you have to decide is it worth to expose it in HA or not.

**Comment by PlusPlus-ua** [comment] 2023-04-28 15:35
I've added new version 0.1.3 with draft of CUBETOUCH 1s support. Can you update to it with HACS?

**Comment by damiano75** [comment] 2023-04-28 16:27
> I've added new version 0.1.3 with draft of CUBETOUCH 1s support. Can you update to it with HACS?

It works!
I have these two switches:
![image](https://user-images.githubusercontent.com/47896789/235202100-46a4d1e2-f559-4795-bb20-2f84f892558a.png)

They should be power saving and tap enable, but they have the same generic name.
Probably they are useless, I will check and let you know.

Thanks a lot for your work

**Comment by christophernewton** [comment] 2023-04-28 22:50
I have the same model number as damiano but cant seem to get mine running.
![image](https://user-images.githubusercontent.com/15189005/235266085-e4c01d59-d69e-4661-9720-2b5fa7d10e4b.png)

It gets discovered but hangs at the setup process
<img width="612" alt="image" src="https://user-images.githubusercontent.com/15189005/235265915-17e1d4f9-ee33-469e-baf8-9c2a44587a44.png">

Logs say its timing out
<img width="1345" alt="image" src="https://user-images.githubusercontent.com/15189005/235266169-cb65bd83-5ee4-4ae2-bec5-d6322ae36619.png">


*What Ive tried*
- unbinding and connecting to cubetouch
- rebinding and connecting to cubetouch
- adding the gateway (expect this to not work, just trying things 😓 )
- uninstalling and reinstalling from hacs
- unlinking in tuya app and re linking

Thanks for setting up the code you have so far do you know of anything else I could try to make this work?

**Comment by PlusPlus-ua** [comment] 2023-04-29 07:01
> do you know of anything else I could try to make this work?

I think the problem is in connection quality, the integration itself has nothing to do with it. Try to move your device closer to your Bluetooth adapter to check.

**Comment by PlusPlus-ua** [comment] 2023-04-30 06:42
@damiano75 have you decided about these two additional switches?

**Comment by damiano75** [comment] 2023-04-30 07:08
> @damiano75 have you decided about these two additional switches?

It seems they are useless, if I switch on them they come back to off after a while.
I have disabled them

**Comment by PlusPlus-ua** [comment] 2023-04-30 11:37
I close the issue, feel free to reopen it if you decide to reactivate these switches.

**Closed by PlusPlus-ua** 2023-04-30 11:37 UTC

**Comment by cyrano1966** [comment] 2023-04-30 13:43
I have been testing this Integration for the last full day and it is working fine on my side. Only noticed that if the Bluetooth Proxy goes down or is disconnected, the Cubetouch does not connect back
