### ISSUE TITLE
500 internal server error

### ISSUE THREAD

**Issue by damiano75** [PlusPlus-ua/ha_tuya_ble#3] opened 2023-04-23 14:32 UTC
Hi,
when I try to add the integration in HA I have this message
![image](https://user-images.githubusercontent.com/47896789/233845792-fb299348-c404-43ee-b38e-ade368d58939.png)

HA version 2023.4.6

In the logs:

```
Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: aiohttp.server
Source: custom_components/tuya_ble/cloud.py:171
Integration: Tuya BLE
First occurred: 15:46:40 (3 occurrences)
Last logged: 16:30:16

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 146, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 148, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 71, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 840, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 868, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/tuya_ble/config_flow.py", line 237, in async_step_user
    await self._manager.build_cache()
  File "/config/custom_components/tuya_ble/cloud.py", line 215, in build_cache
    await self._fill_cache_item(item)
  File "/config/custom_components/tuya_ble/cloud.py", line 171, in _fill_cache_item
    await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/tuya_iot/device.py", line 252, in update_device_list_in_smart_home
    self.update_device_function_cache()
  File "/usr/local/lib/python3.10/site-packages/tuya_iot/device.py", line 300, in update_device_function_cache
    for function in result["functions"]:
KeyError: 'functions'

```

**Comment by ShayaN-1226** [comment] 2023-04-24 11:38
Hi, I got the exact same issue, so far tried rebooting and reinstalling but it didn't help.

**Comment by Cres09** [comment] 2023-04-24 18:19
Hi! Same error here. 
This project was exactly what I was looking for. Thank you very much for your effort.

**Comment by daveyijzermans** [comment] 2023-04-24 21:14
I also have this problem. This log entry appears in tandem:

```
Logger: tuya_iot
Source: /usr/local/lib/python3.10/site-packages/tuya_iot/openmq.py:117
First occurred: 23:08:48 (3 occurrences) 
Last logged: 23:08:50

Unexpected disconnection.7
```

Mysteriously, I've been able to see the configuration wizard once. I tried to go through the steps, but I have Adaprox Fingerbots, so they wouldn't add. Tried to add the product ids following [issue 1](https://github.com/PlusPlus-ua/ha_tuya_ble/issues/1) but since then I couldn't get into the config flow any more. (I tried reinstalling the custom component undoing my changes as well)

**Comment by PlusPlus-ua** [comment] 2023-04-26 09:22
Unfortunately, I can't reproduce the error.

During development, I've seen such error one time. I can't recall what was exactly the reason of the error, but it was something wrong in Tuya IOT credentials.

**Comment by ShayaN-1226** [comment] 2023-04-26 14:17
I tried updating to latest version today. I've got the same error message but different log.
![Screenshot_20230427_001234_Home Assistant](https://user-images.githubusercontent.com/129574650/234604335-c990e25a-d1e4-4fb1-96ae-f76154fa084a.jpg)

Log:
```
This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/tuya_ble/cloud.py:171
Integration: Tuya BLE
First occurred: 12:12:16 AM (3 occurrences)
Last logged: 12:12:45 AM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 146, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 148, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 71, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 840, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 868, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/tuya_ble/config_flow.py", line 242, in async_step_user
    await self._manager.build_cache()
  File "/config/custom_components/tuya_ble/cloud.py", line 215, in build_cache
    await self._fill_cache_item(item)
  File "/config/custom_components/tuya_ble/cloud.py", line 171, in _fill_cache_item
    await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/tuya_iot/device.py", line 252, in update_device_list_in_smart_home
    self.update_device_function_cache()
  File "/usr/local/lib/python3.10/site-packages/tuya_iot/device.py", line 305, in update_device_function_cache
    for status in result["status"]:
KeyError: 'status'

```

**Comment by PlusPlus-ua** [comment] 2023-04-26 16:23
I've changed and simplifying a way in which integration obtains device credentials from Tuya IOT cloud.

Please try new version.

**Comment by jay-jay-s** [comment] 2023-04-26 17:11
> I've changed and simplifying a way in which integration obtains device credentials from Tuya IOT cloud.
> 
> Please try new version.

Installed the new version.  First try: "500 Internal Server Error Server got itself in trouble".  Second try worked, but "No unconfigured devices found".

I have Fingerbot Plus, which doesn't work with the default integration.

**Comment by PlusPlus-ua** [comment] 2023-04-26 17:17
> Second try worked, but "No unconfigured devices found".
> 
> I have Fingerbot Plus, which doesn't work with the default integration.

Does the device in range of your Bluetooth adapter? The error means that Bluetooth adapter see no advertisements from compatible devices. If the device is bound to your Tuya Bluetooth gateway, it's better to unbind it using a mobile app.

**Comment by Cres09** [comment] 2023-04-26 17:59
> Unfortunately, I can't reproduce the error.
> 
> During development, I've seen such error one time. I can't recall what was exactly the reason of the error, but it was something wrong in Tuya IOT credentials.

I can't set up the Tuya Credentials because I can't start the wizard.

**Comment by PlusPlus-ua** [comment] 2023-04-26 18:01
> I can't set up the Tuya Credentials because I can't start the wizard.

Have you updated the integration to last version and restarted HA? Are there any errors in the log?

**Comment by daveyijzermans** [comment] 2023-04-26 18:34
Amazing, it works, via Bluetooth bridge! One more device type freed from cloud control!

Interestingly, in the wizard my API credentials were already filled in (I guess from the official Tuya or LocalTuya integration) Maybe that's what caused the bug in the first place?

**Comment by PlusPlus-ua** [comment] 2023-04-26 18:36
Thank you!

> Interestingly, in the wizard my API credentials were already filled in (I guess from the official Tuya or LocalTuya integration)

Yes, the integration tries to obtain credentials from the official Tuya.

**Comment by damiano75** [comment] 2023-04-28 10:14
Now the integration works, you can close the issue, unfortunately my cubot is not supported.

![image](https://user-images.githubusercontent.com/47896789/235120304-70daa219-b57d-4ea0-907d-c06c269405db.png)

There aren't any switch or controls...

Do you think you should add it in the future?

Anyway thank you for your work

**Comment by PlusPlus-ua** [comment] 2023-04-28 10:19
I close this issue.

> There aren't any switch or controls...
> 
> Do you think you should add it in the future? It is a Cubetouch 1s

Of course, it could be added. Could you please open a new issue?

**Comment by damiano75** [comment] 2023-04-28 10:21
> I close this issue.
> 
> > There aren't any switch or controls...
> > Do you think you should add it in the future? It is a Cubetouch 1s
> 
> Of course, it could be added. Could you please open a new issue?

Ok

**Closed** 2023-04-28 10:21 UTC
